.Dd September 1, 2017
.Dt CHEN 1
.
.Sh NAME
.
.Nm chen
.Nd Edit directory entries with your text editor.
.
.Sh SYNOPSIS
.
.Nm
.
.Sh DESCRIPTION
.
.Nm
lets you edit a list of directory entries with your default text
editor. Any renamed lines will result in renamed file names.
.
.Sh AUTHOR
.An Michel Martens Aq mail@soveran.com
